server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false
    username: root
    password: ice123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: data-analysis-service
mybatis:
  type-aliases-package: org.csu.userservice.dao
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.csu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/


