server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-gtjnr8b4.sql.tencentcdb.com:26126/jobfinding-user-information?characterEncoding=utf8
    username: jobhunter
    password: csubdkei
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-Information-service
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis:
  type-aliases-package: org.csu.Information.dao
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.csu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS